server:
  port: 8080

spring:
  thymeleaf:
    cache: false


  datasource:
#    hikari:
#      driver-class-name: org.mariadb.jdbc.Driver
#      jdbc-url: jdbc:mariadb://localhost:3306/mouse
#      username: root
#      password: 1234
#      connection-timeout: 30000
#      pool-name: HikariCP
#      read-only: false
#      connection-test-query: SELECT 1
    url: jdbc:mariadb://localhost:3306/mouse
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
#        use_sql_comments: true  # JPQL ?? ??
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 100GB

logging.level:
  org.hibernate.sql: debug


#decorator:
#  datasource:
#    p6spy:
#      enable-logging: true

